services:
  database:
    image: postgres:16.3
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
#    ports:
#      - 5432:5432
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - database
    command: bash -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn djavue.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/code
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/vuetify
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "4173:4173"  # Expor a porta 4173 para a rede Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    image: nginx:1.27.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/code/static
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
