services:
  database:
    image: postgres:16.3
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - database
    command: bash -c "
      python manage.py migrate --noinput && 
      python manage.py collectstatic --noinput && 
      gunicorn djavue.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/code

  frontend:
    build:
      context: ./frontend/vuetify
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "4173:4173"  # Expor a porta 4173 para a rede Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.27.0
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default_local:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
