# Generated by Django 5.1.7 on 2025-03-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='slug',
        ),
    ]
